version: '3'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - mynetwork

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
    volumes:
      - ./backend/logs:/app/logs
    environment:
      DB_HOST: mariadb
      DB_USER: root
      DB_PASSWORD: yourpassword
      DB_NAME: yourdatabase
      DB_CONNECTION_LIMIT: 5
      DB_CONNECT_TIMEOUT: 10000
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork

volumes:
  mariadb_data:

networks:
  mynetwork:
